export const UPDATE_CART_DISH_LIST = 'shopCart/UPDATE_CART_DISH_LIST'
export const UPDATE_CART_DISH_SORT_MAP_LIST = 'shopCart/UPDATE_CART_DISH_SORT_MAP_LIST'
export const UPDATE_SHOPID = 'shopCart/UPDATE_SHOPID'
export const UPDATE_TABLE_NUM = 'shopCart/UPDATE_TABLE_NUM'